# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'
pod 'AFNetworking', '0.9.1'
target 'power_of_computing' do
  pod 'Firebase/Auth'
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for power_of_computing

end
