# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'
pod 'AFNetworking', '0.9.1'
target 'power_of_computing' do
  pod 'Firebase/Auth'
  
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for power_of_computing

end
