# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform  :ios, '13.2'
target 'power_of_computing' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for power_of_computing
  pod 'Firebase/Analytics'
  pod 'FirebaseUI'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods


end
